# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nikolay Vasiliev
tagline:          Sideways notes
url:              http://twitter.com/lonlylocly
paginate:         1
baseurl:          /
author:
  name:           Nikolay Vasiliev
  url:            https://twitter.com/lonlylocly
  email:          lonlylocly@yandex.ru

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/lonlylocly/lonlylocly.github.io
